const ProjectsData = [
    {
        title: 'Overstock.com',
        subtitle: 'AMP Featured Product',
        url: 'http://www.overstock.com/',
        desc: 'Accelerate Mobile Page',
        key: 'overstock-amp-featured-product',
        company: 'overstock',
        contributions: ['Coordinate deployments with multiple departments.'],
        techs: ['HTML', 'LESS-CSS', 'JavaScript', 'AMP-Bind'],
        live: false
    },
    {
        title: 'Overstock.com',
        subtitle: 'Admin Portal',
        url: 'http://www.overstock.com/',
        desc: 'Accelerate Mobile Page',
        key: 'overstock-admin-portal',
        company: 'overstock',
        contributions: ['Ground up'],
        techs: ['HTML', 'LESS-CSS', 'JavaScript', 'ReactJs', 'Redux'],
        live: false
    },
    {
        title: 'Overstock.com',
        subtitle: 'Hackathon 2017',
        url: 'http://www.overstock.com/',
        desc: 'Project for the Overstock Hackathon.',
        key: 'overstock-hackathon-2017',
        company: 'overstock',
        contributions: ['Ground up'],
        techs: ['HTML', 'LESS-CSS', 'JavaScript', 'ReactJs', 'Redux'],
        live: false
    },
    {
        title: 'Overstock.com',
        subtitle: 'Rewards for Reviews',
        url: 'https://www.overstock.com/rewards-for-reviews',
        desc: 'Reward users for leaving a qualifying review.',
        key: 'overstock-rewards-for-reviews',
        company: 'overstock',
        contributions: ['Coordinate deployments with multiple departments.'],
        techs: ['HTML', 'LESS-CSS', 'JavaScript', 'jQuery'],
        live: true
    },
    {
        title: 'Overstock.com',
        subtitle: 'Responsive See All Reviews Page',
        url: 'http://www.overstock.com/',
        desc: 'Site that resizes down to mobile devices',
        key: 'overstock-responsive-sarp',
        company: 'overstock',
        contributions: ['I implemented an AB test that resulted in lift during a 2 week period.'],
        techs: ['HTML', 'LESS-CSS', 'JavaScript', 'jQuery', 'Handlbars'],
        live: true
    },
    {
        title: 'Overstock.com',
        subtitle: 'See All Reviews Page Mobile Add To Cart',
        url: 'http://www.overstock.com/',
        desc: 'On mobile devices ad and add to cart popup.',
        key: 'overstock-sarp-mobile-atc',
        company: 'overstock',
        contributions: ['Componentize the ATC functionality into a react module.'],
        techs: ['HTML', 'LESS-CSS', 'JavaScript', 'ReactJs'],
        live: true
    },
    {
        title: 'Overstock.com',
        subtitle: 'Reviews breakout',
        url: 'http://www.overstock.com/',
        desc: 'Allowing a user to leave rating only reviews.',
        key: 'overstock-reviews-breakout',
        company: 'overstock',
        contributions: ['Coordinate deployments with multiple departments.'],
        techs: ['HTML', 'LESS-CSS', 'JavaScript', 'jQuery'],
        live: true
    },
    {
        title: 'Truly Lindsey Photography',
        subtitle: '',
        url: 'http://www.trulylindseyphotography.com/',
        desc: 'Truly Lindsey Photography is my wife\'s photography company. I am helping to brand her company.',
        key: 'truly-lindsey-photography',
        company: 'truly-lindsey-photography',
        contributions: ['Wordpress customization, design and branding.'],
        techs: ['WordPress', 'HTML', 'CSS'],
        live: true
    },
    {
        title: 'Room Choice',
        subtitle: '',
        url: 'http://www.roomchoice.com/',
        desc: 'Room Choice is a student housing property management software that allows you to see room assignments and reservation requests.',
        key: 'roomchoice',
        company: 'roomchoice',
        contributions: ['Full Stack Development', 'Django and python', 'Restful API calls.'],
        techs: ['Python', 'AngularJs', 'JavaScript', 'HTML', 'LESS-CSS'],
        live: true
    },
    {
        title: 'Rooke Capital Management',
        subtitle: '',
        url: 'http://www.rookecapital.com/',
        desc: 'This is a steady downhill race perfect for first time runners, as well as those looking to improve their time. Fun to be had includes saints and sinners aid stations and heaven and heck finish lines.',
        key: 'rooke-capital-management',
        company: 'rooke-capital-management',
        contributions: ['Creationg of registration form', 'authorize.net intergration', 'customization of WordPress theme.'],
        techs: ['PHP', 'WordPress', 'JavaScript', 'jQuery', 'HTML', 'CSS'],
        live: true
    },
    {
        title: 'RGDJanitorial',
        subtitle: '',
        url: 'http://www.rgdjanitorial.com/',
        desc: 'RGD Janitorial has been providing Janitorial Services in Utah for over 17 years.',
        key: 'rgdjanitorial',
        company: 'rgdjanitorial',
        contributions: ['Wordpress theme customization', 'WP Advanced Custom Fields', 'Design'],
        techs: ['PHP', 'WordPress', 'JavaScript', 'HTML', 'CSS'],
        live: true
    },
    {
        title: 'Wedding Website',
        subtitle: '',
        url: 'http://www.wedding.hokihappenings.com/',
        desc: 'This is the wedding website that I made for my wedding.',
        key: 'wedding',
        company: 'wedding',
        contributions: ['Site design and development'],
        techs: ['AngularJs', 'JavaScript', 'HTML', 'SCSS'],
        live: true
    },
    {
        title: 'Eric Aroca',
        subtitle: '',
        url: 'http://www.ericaroca.com/',
        desc: 'This is a steady downhill race perfect for first time runners, as well as those looking to improve their time. Fun to be had includes saints and sinners aid stations and heaven and heck finish lines.',
        key: 'eric-aroca',
        company: 'eric-aroca',
        contributions: ['Creationg of registration form', 'customization of WordPress theme.'],
        techs: ['PHP', 'WordPress', 'JavaScript', 'jQuery', 'HTML', 'CSS'],
        live: true
    },
    {
        title: 'Saints and Sinners Half Marathon and Team Relay',
        subtitle: '',
        url: 'http://www.saintsandsinnershalf.com/',
        desc: 'This is a steady downhill race perfect for first time runners, as well as those looking to improve their time. Fun to be had includes saints and sinners aid stations and heaven and heck finish lines.',
        key: 'saints-and-sinners',
        company: 'saints-and-sinners',
        contributions: ['Creationg of registration form, authorize.net intergration|customization of WordPress theme.'],
        techs: ['PHP|JavaScript|jQuery|HTML|CSS'],
        live: true
    },
    {
        title: 'New Life Recovery',
        subtitle: '',
        url: 'http://www.newlife-recovery.org/',
        desc: 'Creative Media Group is a full service media production house based in Orem|Utah. We specialize in high quality digital video production, post-production, and motion graphics.',
        key: 'new-life-recovery',
        company: 'new-life-recovery',
        contributions: ['Customization of WordPress theme.'],
        techs: ['PHP|WordPress|JavaScript|jQuery|HTML|CSS'],
        live: false
    },
    {
        title: 'Creative Media Education',
        subtitle: '',
        url: 'http://www.cmeducation.org/',
        desc: 'Creative Media Group is a full service media production house based in Orem, Utah. We specialize in high quality digital video production, post-production, and motion graphics.',
        key: 'creative-media-education',
        company: 'creative-media-education',
        contributions: ['Stripe Integration|Front-end and Back-end|integrating courses the custom LMS.'],
        techs: ['AngularJs|PHP|JavaScript|jQuery|HTML|CSS'],
        live: false
    },
    {
        title: 'LavaVolt',
        subtitle: '',
        url: 'http://www.lavavolt.com',
        desc: 'LavaVolt is an online film festival and digital distribution solution for independent filmmakers.',
        key: 'lavavolt',
        company: 'lavavolt',
        contributions: ['All of the back-end|everything from user accounts, to film uploading, to querying from the film library.'],
        techs: ['PHP|JavaScript|jQuery|HTML|CSS'],
        live: true
    },
    {
        title: 'Enspark LMS',
        subtitle: '',
        url: 'http://www.lms.enspark.com',
        desc: 'From Leadership Skills to Time Management, our interactive e-Learning courses make people better.',
        key: 'enspark-lms',
        company: 'enspark',
        contributions: ['Finished the second version of the LMS. Restructured the user account and course tracking database. Made information requests dynamic with page jQuery AJAX.'],
        techs: ['PHP|JavaScript|jQuery|HTML|CSS'],
        live: true
    },
    {
        title: 'First Mile',
        subtitle: '',
        url: 'http://www.enspark.net/internationalfulfillment/',
        desc: 'We provide discounted integrated solutions to ship your products or your customers products for less money.',
        key: 'first-mile',
        company: 'first-mile',
        contributions: ['All back-end. Worked with the Flash developer sending information to and from the mobile app. Creating a delivery route system, "text message like" system, and automated tasks.'],
        techs: ['PHP|AngularJs|JavaScript|jQuery|HTML|CSS'],
        live: true
    },
    {
        title: 'The Putting Tour',
        subtitle: '',
        url: 'http://www.theputtingtour.com',
        desc: 'The Putting Tour at Qualifiers Golf will train your nervous system by challenging you with dozens of such putts in a 30 minute round. It really works!',
        key: 'the-putting-tour',
        company: 'the-putting-tour',
        contributions: ['Created the user account system, sending information to and from the mobile app. Helped to develop the mobile app for the golf kiosk, as well as the bracket system for the online competitions.'],
        techs: ['PHP|JavaScript|jQuery|HTML|CSS'],
        live: true
    },
    {
        title: 'WinInsights',
        subtitle: '',
        url: 'http://www.wininsights.com',
        desc: 'WIN Insights is a Diversity and Inclusion - focused learning management system that delivers training, networking, tools, resources, and analytics.',
        key: 'wininsights',
        company: 'wininsights',
        contributions: ['Hand created a custom blog for communities to converse about their executive and cultural groups. Also created a custom slider, and several WordPress pages.'],
        techs: ['PHP|JavaScript|jQuery|HTML|CSS'],
        live: true
    },
    {
        title: 'Barrier Pest Control',
        subtitle: '',
        url: 'http://www.barrierpc.com',
        desc: 'Barrier Pest Control will proactively conquer your existing pest populations and prevent future invasions.',
        key: 'barrier',
        company: 'barrier',
        contributions: ["Created a cronjob to store customer transactions in a MYSQL database then email a list of those transactions in a daily report to the company owners. Front-end fixes to the WordPress site, fixing styles and updating images. "],
        techs: ['JavaScript|jQuery|HTML|CSS'],
        live: true
    },
    {
        title: 'Enspark',
        subtitle: '',
        url: 'http://www.enspark.com',
        desc: 'From Leadership Skills to Time Management, our interactive e-Learning courses make people better.',
        key: 'enspark',
        company: 'enspark',
        contributions: ['Helping to push the second version of Enspark.com live. Implementing a feed, creating forms, and various front-end fixes.'],
        techs: ['JavaScript|jQuery|HTML|CSS'],
        live: true
    },
    {
        title: 'Utah Casa',
        subtitle: '',
        url: 'http://www.utahcasa.org/',
        desc: 'Casa is a volunteer organization that empowers everyday citizens with the ability to transform the lives of abused and neglected children.',
        key: 'utah-casa',
        company: 'utah-casa',
        contributions: ['Helped to fix the blog functionality and structure in WordPress as well as front-end fixes.'],
        techs: ['PHP|HTML|CSS'],
        live: true
    },
    {
        title: 'Paradigm Life',
        subtitle: '',
        url: 'http://www.paradigmlife.net/',
        desc: 'Infinite Banking is a concept that allows individuals to utilize Permanent Life Insurance in ways that most individuals and even insurance professionals could never have imagined.',
        key: 'paradigm-life',
        company: 'paradigm-life',
        contributions: ['Helped with the WordPress theme and structure architecture.'],
        techs: ['PHP|JavaScript|jQuery|HTML|CSS'],
        live: true
    },
    {
        title: 'Debt Free Planning',
        subtitle: '',
        url: 'http://www.debt-free-planning.com',
        desc: 'Get a Free Online Report and recommended solution to your debt problem.',
        key: 'debt-free-planning',
        company: 'debt-free-planning',
        contributions: ['Front-end construction. Creating a email form for user information requests.'],
        techs: ['PHP,Less-CSS|HTML|JavaScript'],
        live: false
    },
    {
        title: 'Southam Consulting',
        subtitle: '',
        url: 'http://www.southamconsulting.net',
        desc: 'Southam Consulting is a consortium of business specialists in several states who have extensive experience and expertise in helping clients achieve peak performance.',
        key: 'southam-consulting',
        company: 'southam-consulting',
        contributions: ['Creating a email form for user information requests. Other front-end fixes.'],
        techs: ['PHP|CSS|HTML|JavaScript'],
        live: true
    }
];

export default ProjectsData;
