export const AMP = 'AMP';
export const ANGULAR_JS = 'ANGULAR_JS';
export const COFFEE_SCRIPT = 'COFFEE_SCRIPT';
export const CSS = 'CSS';
export const DJANGO = 'DJANGO';
export const GRUNT = 'GRUNT';
export const HANDLEBARS_JS = 'HANDLEBARS_JS';
export const HTML = 'HTML';
export const JAVSCRIPT = 'JAVSCRIPT';
export const JQUERY = 'JQUERY';
export const LESS_CSS = 'LESS_CSS';
export const NODE_JS = 'NODE_JS';
export const PHP = 'PHP';
export const PYTHON = 'PYTHON';
export const REACT_JS = 'REACT_JS';
export const REDUX = 'REDUX';
export const SCSS = 'SCSS';
export const SQL = 'SQL';
export const WEBPACK = 'WEBPACK';
export const WORDPRESS = 'WORDPRESS';

export type TechKeys = {
	AMP: 'AMP';
	ANGULAR_JS: 'ANGULAR_JS';
	COFFEE_SCRIPT: 'COFFEE_SCRIPT';
	CSS: 'CSS';
	DJANGO: 'DJANGO';
	GRUNT: 'GRUNT';
	HANDLEBARS_JS: 'HANDLEBARS_JS';
	HTML: 'HTML';
	JAVSCRIPT: 'JAVSCRIPT';
	JQUERY: 'JQUERY';
	LESS_CSS: 'LESS_CSS';
	NODE_JS: 'NODE_JS';
	PHP: 'PHP';
	PYTHON: 'PYTHON';
	REACT_JS: 'REACT_JS';
	REDUX: 'REDUX';
	SCSS: 'SCSS';
	SQL: 'SQL';
	WEBPACK: 'WEBPACK';
	WORDPRESS: 'WORDPRESS';
};

export type TechFilterType = keyof TechKeys | null | 'all' | 'null';
