import {
	ANGULAR_JS,
	AMP,
	CSS,
	COFFEE_SCRIPT,
	DJANGO,
	GRUNT,
	HANDLEBARS_JS,
	HTML,
	JAVSCRIPT,
	JQUERY,
	LESS_CSS,
	NODE_JS,
	PHP,
	PYTHON,
	REDUX,
	REACT_JS,
	SCSS,
	SQL,
	WEBPACK,
	WORDPRESS,
} from '../../const/Tech.const';

export const filterList = [
	ANGULAR_JS,
	AMP,
	CSS,
	COFFEE_SCRIPT,
	DJANGO,
	GRUNT,
	HANDLEBARS_JS,
	HTML,
	JAVSCRIPT,
	JQUERY,
	LESS_CSS,
	NODE_JS,
	PHP,
	PYTHON,
	REDUX,
	REACT_JS,
	SCSS,
	SQL,
	WEBPACK,
	WORDPRESS,
];

export const ProjectsData = [
	{
        title: 'Hoki Skateboards',
        subtitle: 'React Native Game',
        desc: 'Teaching myself React Native as a passion project',
        itemKey: 'hoki-skateboards-react-native',
        company: 'hoki-skateboards',
        contributions: ['React Native development', 'UI/UX Design', 'Character illustrations'],
        techs: [REACT_JS, CSS],
        learned: '',
        live: false,
    },
	{
		title: 'Chatbooks.com',
		subtitle: 'Book Creation',
		url: 'https://chatbooks.com/app/create?page=web_custom_explainer',
		desc: 'Revamp existing create book page with new UI written in ReactJs',
		itemKey: 'chatbooks-create-page',
		company: 'chatbooks',
		contributions: ['Tie into existing API\'s to create a new book.', 'Create reusable UI components'],
		techs: [REACT_JS, REDUX, JAVSCRIPT, HTML, SCSS],
		learned: '',
		live: true,
	},
	{
		title: 'Chatbooks.com',
        subtitle: 'Cards Quick Flow Sources',
        desc: 'Helping to create individual quickflows for creating platform specific custom books. Customers will come to the quickflow from Instagrams\'s store front, then create a book by picking a data source.',
        itemKey: 'chatbooks-quick-flow-sources',
        company: 'chatbooks',
        contributions: ['Create Branch links for redirecting to IOS or android apps.', 'Create screen for selecting the data source as well as a screen platform specific pages info.'],
		techs: [REACT_JS, REDUX, JAVSCRIPT, HTML, SCSS],
        learned: '',
        live: false,
    },
	{
		title: 'Chatbooks.com',
		subtitle: 'Premium Layflat',
		url: 'https://chatbooks.com/app/create?page=web_custom_explainer',
		desc: 'Enable Premium layflat book types for the desktop. This was a break through for the company as it is a better experience to create premium laylfat sized books at a desktop size.',
		itemKey: 'chatbooks-layflat',
		company: 'chatbooks',
		contributions: ['Tie into existing API\'s to allow for layflat.'],
		techs: [REACT_JS, REDUX, JAVSCRIPT, HTML, SCSS],
		learned: '',
		live: true,
	},
	{
		title: 'Chatbooks.com',
        subtitle: 'Cards Taxonomy Pages',
        desc: 'Creating cards taxonomy pages with categories and search filters.',
        itemKey: 'chatbooks-cards-taxonomy',
        company: 'chatbooks',
        contributions: ['Server-side rendering for SEO value', 'Work closely with designers and marketing', 'Integrating with new APIS'],
		techs: [REACT_JS, REDUX, JAVSCRIPT, HTML, SCSS],
        learned: '',
        live: false,
    },
    {
        title: 'Overstock.com',
        subtitle: 'AMP Featured Product',
        url: 'http://www.overstock.com/',
        desc: 'A version of the search/navigation page was build as an Accelerate Mobile Page for fast loading on mobile devices and for SEO.',
        itemKey: 'overstock-amp-featured-product',
        company: 'overstock',
        contributions: ['Duplicate logic from the mobile product page to create the featured product section on the Search AMP page. Use amp-bind for event triggers when selecting options. Reduce and optimize CSS to fit withing AMP specifications.'],
        techs: [HTML, JAVSCRIPT, AMP, WEBPACK, LESS_CSS],
        learned: '',
        live: false,
    },
    {
        title: 'Overstock.com',
        subtitle: 'Admin Portal',
        url: 'http://www.overstock.com/',
        desc: 'Internal SEO tool that enables business employees to do things such as manipulte seo titles for taxonomy display names.',
        itemKey: 'overstock-admin-portal',
        company: 'overstock',
        contributions: ['I incorporated react router and set the project up to be extendable with future pages/tools.'],
        techs: [REACT_JS, REDUX, NODE_JS, HTML, LESS_CSS, JAVSCRIPT, WEBPACK],
        learned: 'I got a deeper understanding of the the Redux flow.',
        live: false,
    },
    {
        title: 'Overstock.com',
        subtitle: 'Hackathon 2017',
        url: 'https://www.overstock.com/94864/static.html',
        desc: "Project for the Overstock Hackathon. It's goal was to increase the amount of reviews and user generated images.",
        itemKey: 'overstock-hackathon-2017',
        company: 'overstock',
        contributions: ['The initial project was build within a 24 hour period. Our project was chosen as a finalist. We had to get the project to production level quality withing a 3 week time period. It was put into a 50/50 test where user conversion selected the winner. This project really pushed to jump into new stacks that I had never done before and to prioritize time.'],
        techs: [HTML, LESS_CSS, JAVSCRIPT, REACT_JS, REDUX, JQUERY, WEBPACK],
        learned: '',
        live: true,
    },
    {
        title: 'Overstock.com',
        subtitle: 'Rewards for Reviews',
        url: 'https://www.overstock.com/rewards-for-reviews',
        desc: 'Reward users for leaving a qualifying review.',
        itemKey: 'overstock-rewards-for-reviews',
        company: 'overstock',
        contributions: ['Coordinate deployments with multiple departments.'],
        techs: [HTML, LESS_CSS, JAVSCRIPT, JQUERY, HANDLEBARS_JS, GRUNT],
        learned: '',
        live: true,
    },
    {
        title: 'Overstock.com',
        subtitle: 'Responsive See All Reviews Page',
        url: 'http://www.overstock.com/',
        desc: 'Site that resizes down to mobile devices',
        itemKey: 'overstock-responsive-sarp',
        company: 'overstock',
        contributions: ['I implemented an AB test that resulted in lift during a 2 week period.'],
        techs: [HTML, LESS_CSS, JAVSCRIPT, JQUERY, HANDLEBARS_JS, GRUNT],
        learned: 'The A/B site test origianlly failed due to routing errors. I had to be persistant at keeping the conversation going and getting help from the right people.',
        live: true,
    },
    {
        title: 'Overstock.com',
        subtitle: 'See All Reviews Page Mobile Add To Cart',
        url: 'http://www.overstock.com/',
        desc: 'On mobile devices ad and add to cart popup.',
        itemKey: 'overstock-sarp-mobile-atc',
        company: 'overstock',
        contributions: ['Componentize the Add To Cart functionality into a react module.'],
        techs: [HTML, LESS_CSS, JAVSCRIPT, REACT_JS],
        learned: 'This was my first production level ReactJs work.',
        live: true,
    },
    {
        title: 'Overstock.com',
        subtitle: 'Reviews Breakout',
        url: 'http://www.overstock.com/',
        desc: 'Allowing a user to leave rating only reviews.',
        itemKey: 'overstock-reviews-breakout',
        company: 'overstock',
        contributions: ['Coordinate deployments with multiple departments.'],
        techs: [HTML, LESS_CSS, JAVSCRIPT, HANDLEBARS_JS, JQUERY],
        learned: 'This project was a huge undertaking. Perviously at other companies I had been full-stack. This project helped me understand the limitations and resonsibilities of being strictly front-end. I had to learn to coordinate with the back-end and understand what our roles are.',
        live: true,
    },
    {
        title: 'Overstock.com',
        subtitle: 'Star Ratings Color',
        url: 'http://www.overstock.com/',
        desc: 'Rating reviews stars',
        itemKey: 'overstock-rating-review-stars',
        company: 'overstock',
        contributions: ["I was tasked to change all of the star ratings from red to gold. That sounds like a simple task but the amount of coordination was intense. This was one of my first tasks in Overstock's shoppting site, and at a company of this scale. I had to learn the process of many teams, it was a good initiation for me."],
        techs: [HTML, LESS_CSS, JAVSCRIPT, HANDLEBARS_JS, JQUERY],
        learned: "I was able to get a deep dive into Overstock's processes across many different teams.",
        live: true,
    },
    {
        title: 'Overstock.com',
        subtitle: 'Affiliate Links',
        url: 'http://www.overstock.com/',
        desc: 'Embedable affiliate links',
        itemKey: 'oversock-affiliate-links',
        company: 'overstock',
        contributions: ['Took the basic wordpress plugin and rearchitected it.'],
        techs: [JAVSCRIPT, JQUERY, PHP, HTML, LESS_CSS, GRUNT],
        learned: '',
        live: true,
    },
	{
        title: 'LindseyHoki.com',
        subtitle: '',
        url: 'http://www.lindseyhoki.com/',
        desc: 'Lindsey Hoki Photography is my wife\'s photography company. I am helping to brand her company.',
        itemKey: 'lindsey-hoki-photography',
        company: 'lindsey-hoki-photography',
        contributions: ['Wordpress customization', 'Design and branding'],
        techs: [WORDPRESS, HTML, CSS],
        learned: '',
        live: true,
    },
    {
        title: 'Hoki Skateboards',
        subtitle: '',
        url: 'http://www.hokiskateboards.com/',
        desc: 'Passion project skateboard company I am helping to brand her company.',
        itemKey: 'hoki-skateboards',
        company: 'hoki-skateboards',
        contributions: ['Wordpress customization', 'Design and branding','Woocommerce integration'],
        techs: [WORDPRESS, PHP, JQUERY, HTML, CSS, REACT_JS],
        learned: '',
        live: true,
    },
	{
        title: 'Truly Lindsey Photography',
        subtitle: '',
        url: 'http://www.trulylindseyphotography.com/',
        desc: 'Truly Lindsey Photography is my wife\'s photography company. I am helping to brand her company.',
        itemKey: 'truly-lindsey-photography',
        company: 'truly-lindsey-photography',
        contributions: ['Wordpress customization', 'Design and branding'],
        techs: [WORDPRESS, HTML, CSS],
        learned: '',
        live: false,
    },
    {
        title: 'Room Choice',
        subtitle: '',
        url: 'http://www.roomchoice.com/',
        desc: 'Room Choice is a student housing property management software that allows you to see room assignments and reservation requests.',
        itemKey: 'roomchoice',
        company: 'roomchoice',
        contributions: ['Full Stack Development', 'Django and python', 'Restful API calls.'],
        techs: [PYTHON, DJANGO, ANGULAR_JS, JAVSCRIPT, COFFEE_SCRIPT, HTML, LESS_CSS],
        learned: 'At Roomchoice I got my first experience with external developers. I had to learn to communicate effectily with a lot of details. | Previous to this company I had mostly done custom freelance-type work. This was my first time working as an internal dedicated team. I was able to help optimize, cleanup, and really build structure.',
        live: true,
    },
    {
        title: 'Rooke Capital Management',
        subtitle: '',
        url: 'http://www.rookecapital.com/',
        desc: 'This is a steady downhill race perfect for first time runners, as well as those looking to improve their time. Fun to be had includes saints and sinners aid stations and heaven and heck finish lines.',
        itemKey: 'rooke-capital-management',
        company: 'rooke-capital-management',
        contributions: ['Creationg of registration form', 'authorize.net intergration', 'customization of wordpress theme.'],
        techs: [PHP, WORDPRESS, JAVSCRIPT, JQUERY, HTML, CSS],
        learned: '',
        live: true,
    },
    {
        title: 'RGDJanitorial',
        subtitle: '',
        url: 'http://www.rgdjanitorial.com/',
        desc: 'RGD Janitorial has been providing Janitorial Services in Utah for over 17 years.',
        itemKey: 'rgdjanitorial',
        company: 'rgdjanitorial',
        contributions: ['wordpress theme customization', 'WP Advanced Custom Fields', 'Design'],
        techs: [PHP, WORDPRESS, JAVSCRIPT, HTML, CSS],
        learned: '',
        live: true,
    },
    {
        title: 'Wedding Website',
        subtitle: '',
        url: 'http://www.wedding.hokihappenings.com/',
        desc: 'This is the wedding website that I made for my wedding.',
        itemKey: 'wedding',
        company: 'wedding',
        contributions: ['Site design and development'],
        techs: [ANGULAR_JS, JAVSCRIPT, HTML, SCSS],
        learned: 'This was a personal project of mine. I really wanted to present information about my wedding in a nice way.',
        live: true,
    },
    {
        title: 'Eric Aroca',
        subtitle: '',
        url: 'http://www.ericaroca.com/',
        desc: 'This is a steady downhill race perfect for first time runners, as well as those looking to improve their time. Fun to be had includes saints and sinners aid stations and heaven and heck finish lines.',
        itemKey: 'eric-aroca',
        company: 'eric-aroca',
        contributions: ['Creationg of registration form', 'customization of wordpress theme.'],
        techs: [PHP, WORDPRESS, JAVSCRIPT, JQUERY, HTML, CSS],
        learned: '',
        live: false,
    },
    {
        title: 'Saints and Sinners Half Marathon and Team Relay',
        subtitle: '',
        url: 'http://www.saintsandsinnershalf.com/',
        desc: 'This is a steady downhill race perfect for first time runners, as well as those looking to improve their time. Fun to be had includes saints and sinners aid stations and heaven and heck finish lines.',
        itemKey: 'saints-and-sinners',
        company: 'saints-and-sinners',
        contributions: ['Creationg of registration form, authorize.net intergration', 'customization of wordpress theme.'],
        techs: [PHP, JAVSCRIPT, JQUERY, HTML, CSS, SQL],
        learned: '',
        live: true,
    },
    {
        title: 'New Life Recovery',
        subtitle: '',
        url: 'http://www.newlife-recovery.org/',
        desc: 'Creative Media Group is a full service media production house based in Orem, Utah. We specialize in high quality digital video production, post-production, and motion graphics.',
        itemKey: 'new-life-recovery',
        company: 'new-life-recovery',
        contributions: ['Customization of wordpress theme.'],
        techs: [PHP, WORDPRESS, JAVSCRIPT, JQUERY, HTML, CSS],
        learned: '',
        live: false,
    },
    {
        title: 'Creative Media Education',
        subtitle: '',
        url: 'http://www.cmeducation.org/',
        desc: 'Creative Media Group is a full service media production house based in Orem, Utah. We specialize in high quality digital video production, post-production, and motion graphics.',
        itemKey: 'creative-media-education',
        company: 'creative-media-education',
        contributions: ['Stripe Integration', 'Front-end and Back-end', 'integrating courses the custom LMS.'],
        techs: [ANGULAR_JS, PHP, JAVSCRIPT, JQUERY, HTML, CSS],
        learned: '',
        live: false,
    },
    {
        title: 'LavaVolt',
        subtitle: '',
        url: 'http://www.lavavolt.com',
        desc: 'LavaVolt is an online film festival and digital distribution solution for independent filmmakers.',
        itemKey: 'lavavolt',
        company: 'lavavolt',
        contributions: ['All of the back-end', 'everything from user accounts, to film uploading, to querying from the film library.'],
        techs: [PHP, JAVSCRIPT, JQUERY, HTML, CSS],
        learned: '',
        live: true,
    },
    {
        title: 'Enspark LMS',
        subtitle: '',
        url: 'http://www.lms.enspark.com',
        desc: 'From Leadership Skills to Time Management, our interactive e-Learning courses make people better.',
        itemKey: 'enspark-lms',
        company: 'enspark',
        contributions: ['Finished the second version of the LMS. Restructured the user account and course tracking database. Made information requests dynamic with page jquery AJAX.'],
        techs: [PHP, JAVSCRIPT, JQUERY, HTML, CSS],
        learned: 'This is one of my first full-stack projects.',
        live: true,
    },
    {
        title: 'First Mile',
        subtitle: '',
        url: 'http://www.enspark.net/internationalfulfillment/',
        desc: 'We provide discounted integrated solutions to ship your products or your customers products for less money.',
        itemKey: 'first-mile',
        company: 'first-mile',
        contributions: ['All back-end. Worked with the Flash developer sending information to and from the mobile app. Creating a delivery route system, "text message like" system, and automated tasks.'],
        techs: [PHP, ANGULAR_JS, JAVSCRIPT, JQUERY, HTML, CSS],
        learned: '',
        live: true,
    },
    {
        title: 'The Putting Tour',
        subtitle: '',
        url: 'http://www.theputtingtour.com',
        desc: 'The Putting Tour at Qualifiers Golf will train your nervous system by challenging you with dozens of such putts in a 30 minute round. It really works!',
        itemKey: 'the-putting-tour',
        company: 'the-putting-tour',
        contributions: ['Created the user account system, sending information to and from the mobile app. Helped to develop the mobile app for the golf kiosk, as well as the bracket system for the online competitions.'],
        techs: [PHP, JAVSCRIPT, JQUERY, HTML, CSS],
        learned: '',
        live: true,
    },
    {
        title: 'WinInsights',
        subtitle: '',
        url: 'http://www.wininsights.com',
        desc: 'WIN Insights is a Diversity and Inclusion - focused learning management system that delivers training, networking, tools, resources, and analytics.',
        itemKey: 'wininsights',
        company: 'wininsights',
        contributions: ['Hand created a custom blog for communities to converse about their executive and cultural groups. Also created a custom slider, and several wordpress pages.'],
        techs: [PHP, JAVSCRIPT, JQUERY, HTML, CSS],
        learned: '',
        live: true,
    },
    {
        title: 'Barrier Pest Control',
        subtitle: '',
        url: 'http://www.barrierpc.com',
        desc: 'Barrier Pest Control will proactively conquer your existing pest populations and prevent future invasions.',
        itemKey: 'barrier',
        company: 'barrier',
        contributions: ["Created a cronjob to store customer transactions in a MYSQL database then email a list of those transactions in a daily report to the company owners. Front-end fixes to the wordpress site, fixing styles and updating images. "],
        techs: [JAVSCRIPT, JQUERY, HTML, CSS, SQL],
        learned: '',
        live: true,
    },
    {
        title: 'Enspark',
        subtitle: '',
        url: 'http://www.enspark.com',
        desc: 'From Leadership Skills to Time Management, our interactive e-Learning courses make people better.',
        itemKey: 'enspark',
        company: 'enspark',
        contributions: ['Helping to push the second version of Enspark.com live. Implementing a feed, creating forms, and various front-end fixes.'],
        techs: [JAVSCRIPT, JQUERY, HTML, CSS, PHP, SQL],
        learned: '',
        live: true,
    },
    {
        title: 'Utah Casa',
        subtitle: '',
        url: 'http://www.utahcasa.org/',
        desc: 'Casa is a volunteer organization that empowers everyday citizens with the ability to transform the lives of abused and neglected children.',
        itemKey: 'utah-casa',
        company: 'utah-casa',
        contributions: ['Helped to fix the blog functionality and structure in wordpress as well as front-end fixes.'],
        techs: [PHP, HTML, CSS],
        learned: '',
        live: true,
    },
    {
        title: 'Paradigm Life',
        subtitle: '',
        url: 'http://www.paradigmlife.net/',
        desc: 'Infinite Banking is a concept that allows individuals to utilize Permanent Life Insurance in ways that most individuals and even insurance professionals could never have imagined.',
        itemKey: 'paradigm-life',
        company: 'paradigm-life',
        contributions: ['Helped with the wordpress theme and structure architecture.'],
        techs: [PHP, JAVSCRIPT, JQUERY, HTML, CSS, SQL],
        learned: '',
        live: true,
    },
    {
        title: 'Debt Free Planning',
        subtitle: '',
        url: 'http://www.debt-free-planning.com',
        desc: 'Get a Free Online Report and recommended solution to your debt problem.',
        itemKey: 'debt-free-planning',
        company: 'debt-free-planning',
        contributions: ['Front-end construction. Creating a email form for user information requests.'],
        techs: [PHP, LESS_CSS, HTML, JAVSCRIPT],
        learned: '',
        live: false,
    },
    {
        title: 'Southam Consulting',
        subtitle: '',
        url: 'http://www.southamconsulting.net',
        desc: 'Southam Consulting is a consortium of business specialists in several states who have extensive experience and expertise in helping clients achieve peak performance.',
        itemKey: 'southam-consulting',
        company: 'southam-consulting',
        contributions: ['Creating a email form for user information requests. Other front-end fixes.'],
        techs: [PHP, CSS, HTML, JAVSCRIPT],
        learned: '',
        live: true,
    }
];
